"""Password-reset use-cases — no HTTP or DRF dependencies."""

from __future__ import annotations

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.tokens import default_token_generator
from django.core.exceptions import ValidationError as DjangoValidationError
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from services.exceptions import ValidationServiceError

User = get_user_model()


class PasswordResetService:
    """
    Stateless service for self-service password reset.

    Token lifecycle
    ---------------
    Tokens are generated by Django's ``PasswordResetTokenGenerator`` which
    signs (user.pk, user.password, user.last_login, timestamp) with
    ``SECRET_KEY``.  A token is automatically invalidated once the password
    changes — no extra storage required.
    """

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _make_uid(user) -> str:
        return urlsafe_base64_encode(force_bytes(user.pk))

    @staticmethod
    def _user_from_uid(uid: str):
        """Return the User for *uid* or raise ``ValidationServiceError``."""
        try:
            pk = force_str(urlsafe_base64_decode(uid))
            return User.objects.get(pk=pk)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist) as exc:
            raise ValidationServiceError("Invalid or malformed reset link.") from exc

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @staticmethod
    def request_reset(email: str) -> None:
        """
        Generate a password-reset token and dispatch an email to *email*.

        Always returns silently — never reveals whether the address exists
        (prevents user-enumeration).
        """
        try:
            user = User.objects.get(email=email.strip().lower())
        except User.DoesNotExist:
            return  # silent — do not expose whether the email exists

        uid = PasswordResetService._make_uid(user)
        token = default_token_generator.make_token(user)
        frontend_url = getattr(settings, "FRONTEND_URL", "").rstrip("/")
        reset_link = f"{frontend_url}/reset-password/?uid={uid}&token={token}"
        hours_valid = settings.PASSWORD_RESET_TIMEOUT // 3600

        # Queue via Celery — never block the request on SMTP availability.
        from apps.authentication.tasks import send_password_reset_email  # noqa: PLC0415

        send_password_reset_email.delay(
            recipient_email=user.email,
            user_name=user.get_full_name() or user.username,
            reset_link=reset_link,
            uid=uid,
            token=token,
            hours_valid=hours_valid,
        )

    @staticmethod
    def confirm_reset(uid: str, token: str, new_password: str) -> None:
        """
        Validate *uid* + *token* and set *new_password* on the user.

        Raises :exc:`~services.exceptions.ValidationServiceError` for any
        invalid state (bad uid, expired/invalid token, weak password).
        """
        user = PasswordResetService._user_from_uid(uid)

        if not default_token_generator.check_token(user, token):
            raise ValidationServiceError(
                "This password-reset link is invalid or has already been used."
            )

        try:
            validate_password(new_password, user=user)
        except DjangoValidationError as exc:
            raise ValidationServiceError("; ".join(exc.messages)) from exc

        user.set_password(new_password)
        user.save(update_fields=["password"])
