# Generated by Django 5.1.15 on 2026-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantinvitation",
            name="role",
            field=models.CharField(
                default="member", help_text="Role slug to assign on acceptance.", max_length=100
            ),
        ),
    ]
