# Generated by Django 5.2.14 on 2026-05-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
