# Generated by Django 5.1.15 on 2026-06-05 15:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_tenant_schema_name_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text='Feature name, e.g. "procurement_v2_enabled".',
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = global flag (applies to all tenants unless overridden).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("tenant", "name")},
            },
        ),
    ]
