# Generated by Django 5.1.15 on 2026-05-25 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0001_initial"),
        ("tenants", "0003_tenant_schema_name_domain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="usertenantrole",
            index=models.Index(fields=["tenant", "role"], name="rbac_tenant_role_idx"),
        ),
        migrations.AddIndex(
            model_name="usertenantrole",
            index=models.Index(fields=["user", "tenant"], name="rbac_user_tenant_idx"),
        ),
    ]
