# Generated by Django 5.1.15 on 2026-06-05 15:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


def migrate_roles(apps, schema_editor):
    Tenant = apps.get_model("tenants", "Tenant")
    Role = apps.get_model("rbac", "Role")
    UserTenantRole = apps.get_model("rbac", "UserTenantRole")

    # Create default roles for all existing tenants
    for tenant in Tenant.objects.all():
        for slug, meta in {
            "owner": {"name": "Owner", "weight": 30},
            "admin": {"name": "Admin", "weight": 20},
            "member": {"name": "Member", "weight": 10},
        }.items():
            Role.objects.get_or_create(
                tenant=tenant,
                slug=slug,
                defaults={
                    "name": meta["name"],
                    "weight": meta["weight"],
                    "is_default": True,
                },
            )

    # Re-link existing UserTenantRole rows
    for utr in UserTenantRole.objects.all():
        old_slug = utr.old_role
        if not old_slug:
            old_slug = "member"
        old_slug = old_slug.strip().lower()
        role = Role.objects.filter(tenant=utr.tenant, slug=old_slug).first()
        if not role:
            role = Role.objects.filter(tenant=utr.tenant, slug="member").first()
        utr.role = role
        utr.save()


def rollback_roles(apps, schema_editor):
    UserTenantRole = apps.get_model("rbac", "UserTenantRole")
    for utr in UserTenantRole.objects.all():
        if utr.role:
            utr.old_role = utr.role.slug
            utr.save()


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0002_add_composite_indexes"),
        ("tenants", "0004_featureflag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text='Dot/colon-separated action code, e.g. "grn:create".',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Human-readable description."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Display name, e.g. 'Admin'.", max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier, e.g. 'admin'.", max_length=100
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="True for system-seeded roles that should not be deleted.",
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=0, help_text="Hierarchy weight — higher is more privileged."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, related_name="roles", to="rbac.permission"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-weight", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["tenant", "slug"], name="rbac_role_tenant_slug_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("tenant", "slug")},
        ),
        migrations.RenameField(
            model_name="usertenantrole",
            old_name="role",
            new_name="old_role",
        ),
        migrations.AddField(
            model_name="usertenantrole",
            name="role",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="rbac.role",
            ),
        ),
        migrations.RunPython(migrate_roles, rollback_roles),
        migrations.AlterField(
            model_name="usertenantrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="rbac.role",
            ),
        ),
        migrations.RemoveField(
            model_name="usertenantrole",
            name="old_role",
        ),
    ]
