# Generated by Django 5.1.15 on 2026-06-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("login_failed", "Login Failed"),
                    ("password_reset_requested", "Password Reset Requested"),
                    ("password_reset_confirmed", "Password Reset Confirmed"),
                    ("user_registered", "User Registered"),
                    ("user_deleted", "User Deleted (GDPR)"),
                    ("role_assigned", "Role Assigned"),
                    ("role_revoked", "Role Revoked"),
                    ("member_invited", "Member Invited"),
                    ("invitation_accepted", "Invitation Accepted"),
                    ("invitation_revoked", "Invitation Revoked"),
                    ("subscription_created", "Subscription Created"),
                    ("subscription_updated", "Subscription Updated"),
                    ("subscription_canceled", "Subscription Canceled"),
                    ("payment_succeeded", "Payment Succeeded"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
