# Generated by Django 5.1.15 on 2026-06-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_changes_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_confirmed', 'Password Reset Confirmed'), ('user_registered', 'User Registered'), ('user_deleted', 'User Deleted (GDPR)'), ('role_assigned', 'Role Assigned'), ('role_revoked', 'Role Revoked'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], db_index=True, max_length=50),
        ),
    ]
